### PR TITLE
PR - restructure of the repository 

### PR DESCRIPTION
**Pull request by ccosmin97**
Each root folder will contain a different conversion use case.

### CODE REVIEW

**Review by fedorov — CHANGES_REQUESTED** [review]
Please remove all binary files and squash commits to make sure the commit where they were added is not in history. It is very rarely a good idea to add binary files to github repo. Especially in our case, where all of those files can be fetched from IDC with a single bash or python line of code. It took me ~3 attempts to even load the page that lists the changed files!

**Comment by fedorov** [comment]
Dataset published in https://zenodo.org/records/12130276.

Post-conversion, the following patch script was applied to all files to include the DOI. `dcmodify` was compiled using the latest version of DCMTK to account for the recent addition of one of the attributes.

```bash
name=$(basename "$1" .dcm)

~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialProtocolID=doi:10.5281/zenodo.12130276' $1
~/github/dcmtk-build/bin/dcmodify -nb -i 'IssuerOfClinicalTrialProtocolID=DOI' $1
~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialSponsorName=National Cancer Institute' $1
~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialProtocolName=' $1
~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialSiteID=' $1
~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialSiteName=' $1
~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialSubjectID='${name} $1
```

**Comment by ccosmin97** [comment]
@fedorov I will squash the commits and remove the binary files. However, until the DICOM SEG pancreas anottations data is ingested in IDC, I cannot rely on idc-index or IDC tools to fetch the demo SEG binary files. The two options we have as far as I know to remedy this :  

- rely on github releases (put the binary files  there) and fetch them inside the colab notebook
- inside the colab notebook : use tciaclient python package to download the NIFTI SEG files, and use idc-index for the reference DICOM images.

**Comment by ccosmin97** [comment]
> Dataset published in https://zenodo.org/records/12130276.
> 
> Post-conversion, the following patch script was applied to all files to include the DOI. `dcmodify` was compiled using the latest version of DCMTK to account for the recent addition of one of the attributes.
> 
> ```shell
> name=$(basename "$1" .dcm)
> 
> ~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialProtocolID=doi:10.5281/zenodo.12130276' $1
> ~/github/dcmtk-build/bin/dcmodify -nb -i 'IssuerOfClinicalTrialProtocolID=DOI' $1
> ~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialSponsorName=National Cancer Institute' $1
> ~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialProtocolName=' $1
> ~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialSiteID=' $1
> ~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialSiteName=' $1
> ~/github/dcmtk-build/bin/dcmodify -nb -i 'ClinicalTrialSubjectID='${name} $1
> ```

@fedorov The zenodo record description needs to be edited, the provided  github link for codebase has changed,
from `https://github.com/ImagingDataCommons/pancreas_CT_TO_DICOM.` to `https://github.com/ImagingDataCommons/idc-dicom-seg-conversions`

**Comment by fedorov** [comment]
> However, until the DICOM SEG pancreas anottations data is ingested in IDC, I cannot rely on idc-index or IDC tools to fetch the demo SEG binary files. The two options we have as far as I know to remedy this :

200+ binary files you included are corresponding to the CT series, not SEG, if I remember correctly.

About SEG, once they are published, you can update to pull SEG from IDC for the demo.

**Comment by fedorov** [comment]
> The zenodo record description needs to be edited, the provided github link for codebase has changed,
from https://github.com/ImagingDataCommons/pancreas_CT_TO_DICOM. to https://github.com/ImagingDataCommons/idc-dicom-seg-conversions

done

**Comment by ccosmin97** [comment]
> > However, until the DICOM SEG pancreas anottations data is ingested in IDC, I cannot rely on idc-index or IDC tools to fetch the demo SEG binary files. The two options we have as far as I know to remedy this :
> 
> 200+ binary files you included are corresponding to the CT series, not SEG, if I remember correctly.
> 
> About SEG, once they are published, you can update to pull SEG from IDC for the demo.

sure, I will squash the commits and  remove the binary files.
I will update the notebooks once the DICOM SEG pancreas annotations are in IDC.

**Pull request closed without merging**
